export const GET_COMMENTS = 'GET_COMMENTS';
export const GOT_COMMENTS = 'GOT_COMMENTS';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADDED_COMMENT = 'ADDED_COMMENT';

export const UPDATE_COMMENT='UPDATE_COMMENT';
export const UPDATED_COMMENT='UPDATED_COMMENT';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETED_COMMENT = 'DELETED_COMMENT';